services:
  db:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tgbot_nakama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9441:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    restart: always
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"

volumes:
  db-data:
